INSERT INTO department (name)
VALUES('Sales and Marketing'),
      ('Quality Management'),
      ('Production Control'),
      ('Engineering'),
      ('Research and Development'),
      ('Human Resources'),
      ('Accounting'),
      ('Legal');
      ('IT'),
      ('Advertising'),
      ('Business Development'),
      ('Customer Service'),
      ('Finance');

INSERT INTO role (title, salary, department_id)
VALUES('Accountant', 63000, 7),
      ('Lawyer', 100000, 8),
      ('Sales Manager', 80000, 1),
      ('Marketing Manager', 80000, 1),
      ('Quality Control Manager', 80000, 2),
      ('Accounting Manager', 92000, 7),
      ('Production Manager', 80000, 3),
      ('Engineering Manager', 80000, 4),
      ('Research and Development Manager', 80000, 5),
      ('Human Resources Manager', 80000, 6),
      ('IT Manager', 80000, 9),
      ('Advertising Manager', 80000, 10),
      ('Business Development Manager', 80000, 11),
      ('Customer Service Manager', 80000, 12),
      ('Quality Control Representative', 45000, 2),
      ('Finance Manager', 80000, 13),
      ('Engineering Representative', 45000, 4),
      ('Research and Development Representative', 45000, 5),
      ('Advertising Representative', 45000, 10),
      ('Customer Service Representative', 45000, 12),
      ('Finance Representative', 45000, 13);

INSERT INTO employee (first_name, last_name, role_id, manager_id)
VALUES('John', 'Steel', 15, 2),
      ('Mike', 'Smith', 5),
      ('Sally', 'Jones', 1, 5),
      ('Jane', 'Doe', 2),
      ('Bob', 'Brown', 6),
      ('Joe', 'Black', 3),
      ('Mary', 'White', 4),
      ('Tom', 'Green', 7),
      ('Bill', 'Grey', 8),
      ('Jill', 'Pink', 9),
      ('Jack', 'Orange', 13),
      ('Jen', 'Purple', 10),
      ('Jenny', 'Red', 18, 10),
      ('Jenifer', 'Yellow',16 ),
      ('Jenette', 'Blue', 14),
      ('Jenise', 'Brown', 11),
      ('Jenine', 'Green', 17, 9),
      ('Jenise', 'Pink', 19, 19),
      ('Jenette', 'Orange', 12),
      ('Jenifer', 'Purple', 20, 15),
      ('Jenny', 'Red', 21, 14);
